version: '3.8'

services:
  odoo:
    image: odoo:17
    container_name: odoo_app
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - ./custom-addons:/mnt/custom-addons
    environment:
      HOST: ${DB_HOST}
      PORT: ${DB_PORT}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
      PGHOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_NAME}
      PGSSLMODE: ${DB_SSLMODE}