[options]
admin_passwd = $pbkdf2-sha512$600000$C8F4zznnvFdKKUXoPef8/w$oDcryzhTAC96I1t6HU/KVhbgr6Dn8BBNv4CygF.kh5/E1qTJjmB1Hrx9H..vzFvBdd0hZcF9yJBUZGYziBdnlQ
db_host = db
db_port = 5432
db_user = odoo
db_password = strongpassword
addons_path = /mnt/extra-addons,/mnt/custom-addons
log_level = info

