services:
  - type: web
    name: fango-food-odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /web/login
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: DB_HOST
        value: dpg-d730t699fqoc73cbm1dg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: fango_food_user
      - key: DB_PASSWORD
        value: YoswlrOBkW0MLnuwceImVDntzNDgEroJ
      - key: DB_NAME
        value: fango_food
      - key: DB_SSLMODE
        value: require
