services:
  - type: web
    name: fango-food-odoo
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: odoo --http-port=$PORT --db_host=$DB_HOST --db_port=$DB_PORT --db_user=$DB_USER --db_password=$DB_PASSWORD --database=$DB_NAME --db_sslmode=$DB_SSLMODE
    plan: starter
    autoDeploy: true
    healthCheckPath: /web/login
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 10
    envVars:
      - key: DB_HOST
        value: dpg-d730t699fqoc73cbm1dg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: fango_food_user
      - key: DB_PASSWORD
        value: YoswlrOBkW0MLnuwceImVDntzNDgEroJ
      - key: DB_NAME
        value: fango_food
      - key: DB_SSLMODE
        value: require
